version: "~> 1.0"
os: linux
language: shell
services:
  - docker
notifications:
  email:
    on_success: never
    on_failure: never
  slack:
    if: branch = master
    rooms:
      secure: el8DAASnC2Y5ovuSNtbmOwkDuhtZTDpFWCsbe83lafGlyAerzczqqzDxoqMfq35N37ImaFa35C24fCaZBBvpaH5BLHw/haQOWNW1M6k9vy/sxaPkxJWu9xsPx0RnxCqDC5JfoZZStwjzhi+sPVKyR5ypYKlXGYpp6gG5JWJLfzs8hH/KkI/KkIZ/2B6E7vsJcvY+ALqq+FgaLyVZcWm4lfwYrXvBHc5CaXlQrMGfBGo31FbbFI1kUjls7XvvNR+7x5NoM/blpuc44ZT5/xlZYIOZ/taWUB9m23QuQjAPQ3z9PYxkDB5fIITTe4oG3AuJwZDsRyr8sPkLmpl/QEnVAnemxeQfobz24UxXSHJFz6S3JAa2aDaJdmggNetlHLA9aXeuzOtNPvyta45/d3U/OKobV4Xbc4+S3sh+OoPYcIng7s8qrrE6m1dbBIoPKxIVN4+9ImXHeiLTceaHhcs07Gcpg1i+bIZ/e3P1eNbh1P86fHXDibWRYB/ZMePV7YQ6EV0brG/djL+Ip4mna3RMjAuzIuhNSkJVqR91wwoVro9fh5IOALKb6p0XRBarGor8/Zd3M5aEzHPtbD+MpTsQ6xZPZO6D+ZK0dvX9gTsYMCg4YN0rqS4USnuia4RnpZnu9P2xMdPJm1FwashLjYdsPO5yGdJ4Bv5UsaD8uRarebE=
    template:
      - "%{commit_subject}"
      - build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) @%{branch}
      - by %{author} %{result} in %{duration}
    on_success: change
    on_failure: always
env:
  jobs:
    - MAVEN_TAG='latest'     REPO='s2i-builder-maven' TAG='latest'
    - MAVEN_TAG='3-jdk-14'   REPO='s2i-builder-maven' TAG='3-jdk-14'
    - MAVEN_TAG='3-jdk-13'   REPO='s2i-builder-maven' TAG='3-jdk-13'
    - MAVEN_TAG='3-jdk-12'   REPO='s2i-builder-maven' TAG='3-jdk-12'
    - MAVEN_TAG='3-jdk-11'   REPO='s2i-builder-maven' TAG='3-jdk-11'
    - MAVEN_TAG='3-jdk-10'   REPO='s2i-builder-maven' TAG='3-jdk-10'
    - MAVEN_TAG='3-jdk-9'    REPO='s2i-builder-maven' TAG='3-jdk-9'
    - MAVEN_TAG='3-jdk-8'    REPO='s2i-builder-maven' TAG='3-jdk-8'
  global:
    - secure: TSzB08OmlOviBB0ZWXVZbuedEEBzd9yQ10mY4K6WXw+5LiCxUGcgUwWywgR5lHF89+GjpKG+iRXHIplXl4tqSYSRXx1JP4h6BFj9vgMct0xIDOnVLhj5hhGQVM7zNf5ni3JNfW08ZkCEcBkMFVwszndYrT5mXYzAMnDUXzlIc6U65BrkPIt1uL1nd2rr3PFRjlyKENNnZ3vefjPO7JmqV+nBNWL5Fm14lumx7Fkb+eGq0FmJYABraAc+B5swO1DWvnW6tJdMCnbL5iJrwQSDoWn+eYXwukxV1XYdfkVYR2vGEBXi27mAK79ib/c15gP5vNc+KS1LQtJAJubbBVgfDr/USXl2LieE9V6J2PzqV1G7RrwWr2DKLrKT9HbBn8BB+KVnskGnKGTljEpM1xvbCYee7vT4eMRuvzCsTTfdHJ/aATp5XRx1TXdH7Xt2CO2w9p18KImT+X24GQd7ZOutBA2td7n8k9RPBvHHPB45xGOtiCZsBC3BfqMn7aqnH7UQlqLFrVWRfRuihvhP8LNrB2+6459jMcWIoUGXFnSOrFOVfdlHmorV6KP6msP3xMUrDyixNK4eLcC4DPNzYTOw4Cwj8Viy/jmumE+IKa+/FF+G9K2JdonJNlypihii/uoFCnYtKkiQq/vtNBA0ZtNcIqWXymDCGUQpcV+Kwp9hg7Q=
before_install:
  - openssl aes-256-cbc -K $encrypted_4b36a787d569_key -iv $encrypted_4b36a787d569_iv
    -in .travis/token.enc -out .travis/token -d
  - export PATH=$(pwd)/.travis:$PATH
install:
  - docker run --rm -v $(pwd)/.travis:/mnt quay.io/openshift/origin-cli:latest cp /usr/bin/oc /mnt/oc
script:
  - |
    set -e
    if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then
      cat .travis/token | xargs -I % oc login --token=% --server=${OCP_API} --insecure-skip-tls-verify
      ci.sh ${TRAVIS_BRANCH} ${MAVEN_TAG}
      if [ "${TRAVIS_BRANCH}" == "master" ]; then
        sed -i "s/FROM maven:.*/FROM maven:${MAVEN_TAG}/g" Dockerfile
        docker build -t ${ORGANIZATION}/${REPO}:${TAG} --no-cache .
        echo "${DOCKER_PASS}" | docker login -u "${DOCKER_USER}" --password-stdin
        docker push ${ORGANIZATION}/${REPO}
      fi
    else
      echo "CI doesn't run for pull request. For further information see: https://docs.travis-ci.com/user/pull-requests/#pull-requests-and-security-restrictions"
    fi
